/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/epics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EpicDto"];
                        "application/json": components["schemas"]["EpicDto"];
                        "text/json": components["schemas"]["EpicDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEpicRequest"];
                    "text/json": components["schemas"]["UpdateEpicRequest"];
                    "application/*+json": components["schemas"]["UpdateEpicRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEpicRequest"];
                    "text/json": components["schemas"]["CreateEpicRequest"];
                    "application/*+json": components["schemas"]["CreateEpicRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/epics/{id}/reorder-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                    "text/json": {
                        [key: string]: number | string;
                    };
                    "application/*+json": {
                        [key: string]: number | string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/by-status/{statusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "AuthData.OrganizationId"?: number | string;
                    "AuthData.UserId"?: string;
                    StatusId?: number | string;
                    SearchString?: string;
                    Filters?: {
                        [key: string]: components["schemas"]["AttributeFilterValue"];
                    };
                    "Sorting.Direction"?: components["schemas"]["SortingDirection"];
                    Skip?: number | string;
                    Take?: number | string;
                };
                header?: never;
                path: {
                    statusId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchResultOfIssueListDto"];
                        "application/json": components["schemas"]["BatchResultOfIssueListDto"];
                        "text/json": components["schemas"]["BatchResultOfIssueListDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/by-status/{statusId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    statusId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetIssuesRequest"];
                    "text/json": components["schemas"]["GetIssuesRequest"];
                    "application/*+json": components["schemas"]["GetIssuesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchResultOfIssueListDto"];
                        "application/json": components["schemas"]["BatchResultOfIssueListDto"];
                        "text/json": components["schemas"]["BatchResultOfIssueListDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IssueDetailDto"];
                        "application/json": components["schemas"]["IssueDetailDto"];
                        "text/json": components["schemas"]["IssueDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: int64 */
                        "AuthData.OrganizationId"?: number | string;
                        /** Format: uuid */
                        "AuthData.UserId"?: string;
                        /** Format: int32 */
                        "IssueKey.Number"?: number | string;
                        "IssueKey.SpaceKey"?: string;
                        Content?: string;
                        /** Format: uuid */
                        AssigneeId?: string;
                        AttributeValues?: components["schemas"]["AttributeValue"][];
                        RemoveAttachmentIds?: string[];
                        AddFiles?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetBoardRequest"];
                    "text/json": components["schemas"]["GetBoardRequest"];
                    "application/*+json": components["schemas"]["GetBoardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ColumnIssues"][];
                        "application/json": components["schemas"]["ColumnIssues"][];
                        "text/json": components["schemas"]["ColumnIssues"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: int64 */
                        "AuthData.OrganizationId"?: number | string;
                        /** Format: uuid */
                        "AuthData.UserId"?: string;
                        /** Format: int64 */
                        StatusId?: number | string;
                        /** Format: uuid */
                        AssigneeId?: string;
                        Content?: string;
                        AttributeValues?: components["schemas"]["AttributeValue"][];
                        Files?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                    "text/json": components["schemas"]["SearchRequest"];
                    "application/*+json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShortPaginatedResultOfSearchIssueDto"];
                        "application/json": components["schemas"]["ShortPaginatedResultOfSearchIssueDto"];
                        "text/json": components["schemas"]["ShortPaginatedResultOfSearchIssueDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "AuthData.OrganizationId"?: number | string;
                    "AuthData.UserId"?: string;
                    SpaceId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EpicSummary"][];
                        "application/json": components["schemas"]["EpicSummary"][];
                        "text/json": components["schemas"]["EpicSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement/space/{id}/to-organization/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    organizationId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement/space/{id}/epics-to-space/{newSpaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    newSpaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement/epic/{id}/to-space/{newSpaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    newSpaceId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement/organization/{id}/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DestinationSpace"][];
                        "application/json": components["schemas"]["DestinationSpace"][];
                        "text/json": components["schemas"]["DestinationSpace"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement/issue/{key}/move-to-status/{statusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                    statusId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationListDto"][];
                        "application/json": components["schemas"]["OrganizationListDto"][];
                        "text/json": components["schemas"]["OrganizationListDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                    "text/json": components["schemas"]["CreateOrganizationRequest"];
                    "application/*+json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateOrganizationResponse"];
                        "application/json": components["schemas"]["CreateOrganizationResponse"];
                        "text/json": components["schemas"]["CreateOrganizationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditOrganizationRequest"];
                    "text/json": components["schemas"]["EditOrganizationRequest"];
                    "application/*+json": components["schemas"]["EditOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/join/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/regenerate-join-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/join-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/revoke-access/{organizationUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationUserId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/permissions/{organizationUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationUserId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserPermissions"];
                        "application/json": components["schemas"]["UserPermissions"];
                        "text/json": components["schemas"]["UserPermissions"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationUserId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPermissionsRequest"];
                    "text/json": components["schemas"]["SetPermissionsRequest"];
                    "application/*+json": components["schemas"]["SetPermissionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/permittable-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PermittableSpace"][];
                        "application/json": components["schemas"]["PermittableSpace"][];
                        "text/json": components["schemas"]["PermittableSpace"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"];
                        "application/json": components["schemas"]["OrganizationDto"];
                        "text/json": components["schemas"]["OrganizationDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationMember"][];
                        "application/json": components["schemas"]["OrganizationMember"][];
                        "text/json": components["schemas"]["OrganizationMember"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AttributeDto"][];
                        "application/json": components["schemas"]["AttributeDto"][];
                        "text/json": components["schemas"]["AttributeDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttributeRequest"];
                    "text/json": components["schemas"]["CreateAttributeRequest"];
                    "application/*+json": components["schemas"]["CreateAttributeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/attributes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAttributeRequest"];
                    "text/json": components["schemas"]["UpdateAttributeRequest"];
                    "application/*+json": components["schemas"]["UpdateAttributeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceListDto"][];
                        "application/json": components["schemas"]["SpaceListDto"][];
                        "text/json": components["schemas"]["SpaceListDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSpaceRequest"];
                    "text/json": components["schemas"]["CreateSpaceRequest"];
                    "application/*+json": components["schemas"]["CreateSpaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceDetailsDto"];
                        "application/json": components["schemas"]["SpaceDetailsDto"];
                        "text/json": components["schemas"]["SpaceDetailsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSpaceRequest"];
                    "text/json": components["schemas"]["UpdateSpaceRequest"];
                    "application/*+json": components["schemas"]["UpdateSpaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{id}/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EpicListDto"][];
                        "application/json": components["schemas"]["EpicListDto"][];
                        "text/json": components["schemas"]["EpicListDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpaceMember"][];
                        "application/json": components["schemas"]["SpaceMember"][];
                        "text/json": components["schemas"]["SpaceMember"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    "AuthData.OrganizationId"?: number | string;
                    "AuthData.UserId"?: string;
                    EpicId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageStatusDto"][];
                        "application/json": components["schemas"]["MessageStatusDto"][];
                        "text/json": components["schemas"]["MessageStatusDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStatusRequest"];
                    "text/json": components["schemas"]["CreateStatusRequest"];
                    "application/*+json": components["schemas"]["CreateStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditStatusRequest"];
                    "text/json": components["schemas"]["EditStatusRequest"];
                    "application/*+json": components["schemas"]["EditStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth-via-mini-app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthenticateViaStringInitDataRequest"];
                    "text/json": components["schemas"]["AuthenticateViaStringInitDataRequest"];
                    "application/*+json": components["schemas"]["AuthenticateViaStringInitDataRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TelegramWidgetAuthRequest"];
                    "text/json": components["schemas"]["TelegramWidgetAuthRequest"];
                    "application/*+json": components["schemas"]["TelegramWidgetAuthRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MiniAppUser"];
                    "text/json": components["schemas"]["MiniAppUser"];
                    "application/*+json": components["schemas"]["MiniAppUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings/epic-sort-order/{epicSortOrder}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    epicSortOrder: components["schemas"]["EpicSortOrder"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminAccessLevel: number;
        AttachmentType: number;
        AttributeDto: {
            /** Format: int64 */
            id?: number | string;
            name: string;
            color: string;
            type: components["schemas"]["AttributeType"];
            listValues: components["schemas"]["AttributeListValueDto"][];
        };
        AttributeFilterValue: components["schemas"]["AttributeFilterValueStringAttributeFilterValue"] | components["schemas"]["AttributeFilterValueEnumAttributeFilterValue"];
        AttributeFilterValueEnumAttributeFilterValue: {
            /** @enum {string} */
            $type?: "enum";
            ids: (number | string)[];
        };
        AttributeFilterValueStringAttributeFilterValue: {
            /** @enum {string} */
            $type?: "string";
            searchString: string;
        };
        AttributeListValueDto: {
            /** Format: int64 */
            id?: number | string;
            name: string;
        };
        AttributeType: number;
        AttributeValue: components["schemas"]["AttributeValueEnumAttributeValue"] | components["schemas"]["AttributeValueStringAttributeValue"];
        AttributeValueEnumAttributeValue: {
            /** @enum {string} */
            $type?: "enum";
            /** Format: int64 */
            valueId: number | string;
            /** Format: int64 */
            attributeId?: number | string;
        };
        AttributeValueStringAttributeValue: {
            /** @enum {string} */
            $type?: "string";
            value: string;
            /** Format: int64 */
            attributeId?: number | string;
        };
        AuthenticateViaStringInitDataRequest: {
            initData: string;
        };
        BatchResultOfIssueListDto: {
            /** Format: int64 */
            offset?: number | string;
            hasNext?: boolean;
            data: components["schemas"]["IssueListDto"][];
        };
        ColumnIssues: {
            /** Format: int64 */
            statusId: number | string;
            items: components["schemas"]["InitialBatchResultOfIssueListDto"];
        };
        ColumnSummary: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            /** Format: int32 */
            count: number | string;
        };
        CreateAttributeRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            name: string;
            color: string;
            type?: components["schemas"]["AttributeType"];
            listValues?: null | components["schemas"]["NewAttributeListValueDto"][];
        };
        CreateEpicRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            spaceId?: number | string;
            name: string;
            color: string;
        };
        CreateOrganizationRequest: {
            /** Format: uuid */
            userId?: string;
            name: string;
            slug: string;
            color: string;
        };
        CreateOrganizationResponse: {
            /** Format: int64 */
            id?: number | string;
            slug: string;
            slugPostfix: string;
        };
        CreateSpaceRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            name: string;
            color: string;
            key: string;
        };
        CreateStatusRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            name: string;
            color: string;
            /** Format: int64 */
            epicId: number | string;
        };
        DestinationSpace: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: string;
        };
        DetailIssueAttributeDto: {
            /** Format: int64 */
            id: number | string;
            type: components["schemas"]["AttributeType"];
            name: string;
            value: string;
            color: string;
            listValues: components["schemas"]["IssueAttributeListValueDto"][];
        };
        DirectSpaceAccessLevel: {
            canRead?: boolean;
            canUpdate?: boolean;
            canDelete?: boolean;
            canCreateEpics?: boolean;
            canUpdateEpics?: boolean;
            canDeleteEpics?: boolean;
            canCreateIssues?: boolean;
            canUpdateIssues?: boolean;
            canDeleteIssues?: boolean;
        };
        EditOrganizationRequest: {
            /** Format: int64 */
            id?: number | string;
            /** Format: uuid */
            userId?: string;
            name: string;
            slug: string;
            color: string;
        };
        EditStatusRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            id?: number | string;
            color: string;
            name: string;
        };
        EpicDto: {
            name: string;
            color: null | string;
            statuses?: components["schemas"]["StatusDto"][];
            canCreateIssues: boolean;
            canDeleteIssues: boolean;
            canUpdateIssues: boolean;
            canUpdate?: boolean;
            canDelete?: boolean;
        };
        EpicListDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            /** Format: date-time */
            touchedAt: string;
            isDefault: boolean;
        };
        EpicSortOrder: number;
        EpicSummary: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            columns: components["schemas"]["ColumnSummary"][];
            /** Format: date-time */
            touchedAt: string;
            isDefault: boolean;
        };
        GetBoardRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            epicId?: number | string;
            /** Format: int32 */
            take?: number | string;
            searchString?: null | string;
            filters?: {
                [key: string]: components["schemas"]["AttributeFilterValue"];
            };
            sorting?: null | components["schemas"]["IssueSorting"];
        };
        GetIssuesRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            statusId?: number | string;
            searchString?: null | string;
            filters?: {
                [key: string]: components["schemas"]["AttributeFilterValue"];
            };
            sorting?: null | components["schemas"]["IssueSorting"];
            /** Format: int32 */
            skip?: number | string;
            /** Format: int32 */
            take?: number | string;
        };
        GlobalAccessLevels: {
            canRead?: boolean;
            canCreateSpaces?: boolean;
            canUpdateSpaces?: boolean;
            canDeleteSpaces?: boolean;
            canCreateEpics?: boolean;
            canUpdateEpics?: boolean;
            canDeleteEpics?: boolean;
            canCreateIssues?: boolean;
            canUpdateIssues?: boolean;
            canDeleteIssues?: boolean;
        };
        /** Format: binary */
        IFormFile: string;
        InitialBatchResultOfIssueListDto: {
            /** Format: int64 */
            totalCount?: number | string;
            /** Format: int64 */
            offset?: number | string;
            hasNext?: boolean;
            data: components["schemas"]["IssueListDto"][];
        };
        IssueAttributeListValueDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
        };
        IssueDetailDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: uuid */
            assigneeId: string;
            assignee: string;
            assigneeInitial: string;
            assigneeColor: string;
            /** Format: date-time */
            time: string;
            /** Format: date-time */
            updatedAt: string;
            ownerDisplayName: null | string;
            ownerInitials?: null | string;
            ownerColor: string;
            content: null | string;
            /** Format: int64 */
            epicId: number | string;
            epicName: null | string;
            epicColor: null | string;
            /** Format: int64 */
            statusId: number | string;
            statusName: null | string;
            statusColor: null | string;
            /** Format: int64 */
            spaceId: number | string;
            spaceName: string;
            spaceColor: string;
            canEdit: boolean;
            key: string;
            attributeValues: components["schemas"]["DetailIssueAttributeDto"][];
            media: components["schemas"]["MediaInfo"][];
        };
        IssueListAttributeDto: {
            value: string;
            color: string;
        };
        IssueListDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: date-time */
            time: string;
            assignee: string;
            key: string;
            assigneeInitial?: null | string;
            assigneeColor: string;
            content: null | string;
            /** Format: int64 */
            epicId: number | string;
            /** Format: int64 */
            statusId: number | string;
            /** Format: int64 */
            spaceId: number | string;
            attributes?: components["schemas"]["IssueListAttributeDto"][];
        };
        IssueProperty: number;
        IssueSorting: components["schemas"]["IssueSortingByAttributeIssueSorting"] | components["schemas"]["IssueSortingByPropertyIssueSorting"];
        IssueSortingByAttributeIssueSorting: {
            /** @enum {string} */
            $type?: "attribute";
            /** Format: int64 */
            attributeId?: number | string;
            direction?: components["schemas"]["SortingDirection"];
        };
        IssueSortingByPropertyIssueSorting: {
            /** @enum {string} */
            $type?: "property";
            property?: components["schemas"]["IssueProperty"];
            direction?: components["schemas"]["SortingDirection"];
        };
        LoginRequest: {
            /** Format: uuid */
            userId?: string;
            /** Format: int64 */
            organizationId?: number | string;
        };
        MediaInfo: {
            /** Format: uuid */
            previewFileId?: null | string;
            /** Format: uuid */
            originalFileId?: string;
            type?: components["schemas"]["AttachmentType"];
        };
        MessageStatusDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            /** Format: int32 */
            count: number | string;
        };
        MiniAppUser: {
            /** Format: int64 */
            id?: number | string;
            username?: null | string;
            languageCode?: null | string;
            firstName?: null | string;
            lastName?: null | string;
        };
        NameAndColor: {
            name: string;
            color: string;
        };
        NewAttributeListValueDto: {
            name: string;
        };
        OrganizationAuthData: {
            /** Format: int64 */
            organizationId?: number | string;
            /** Format: uuid */
            userId?: string;
        };
        OrganizationDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            canCreateSpaces: boolean;
            canMassMove: boolean;
            canManage: boolean;
            canManageAttributes: boolean;
            slug: string;
            slugPostfix: string;
            preferences?: components["schemas"]["UserOrganizationPreferencesResponse"];
        };
        OrganizationListDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            canUpdate: boolean;
            canDelete: boolean;
            isPersonal: boolean;
            canCreateSpaces: boolean;
            slug: string;
            slugPostfix: string;
        };
        OrganizationMember: {
            /** Format: int64 */
            organizationUserId?: number | string;
            displayName: string;
            initials: string;
            color: string;
            isOwner: boolean;
            adminAccessLevel: components["schemas"]["AdminAccessLevel"];
        };
        PermittableSpace: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: string;
            isDefault: boolean;
        };
        SearchIssueDto: {
            epic: components["schemas"]["NameAndColor"];
            status: null | components["schemas"]["NameAndColor"];
            space: components["schemas"]["NameAndColor"];
            canEdit: boolean;
            /** Format: int64 */
            id: number | string;
            /** Format: date-time */
            time: string;
            assignee: string;
            key: string;
            assigneeInitial?: null | string;
            assigneeColor: string;
            content: null | string;
            /** Format: int64 */
            epicId: number | string;
            /** Format: int64 */
            statusId: number | string;
            /** Format: int64 */
            spaceId: number | string;
            attributes?: components["schemas"]["IssueListAttributeDto"][];
        };
        SearchRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            epicIds?: (number | string)[];
            spaceIds?: (number | string)[];
            searchString?: null | string;
            /** Format: int32 */
            page?: number | string;
            /** Format: int32 */
            perPage?: number | string;
            filters?: {
                [key: string]: components["schemas"]["AttributeFilterValue"];
            };
            sorting?: null | components["schemas"]["IssueSorting"];
        };
        SetPermissionsRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            organizationUserId?: number | string;
            userPermissions: components["schemas"]["UserPermissions"];
        };
        ShortPaginatedResultOfSearchIssueDto: {
            /** Format: int64 */
            page: number | string;
            /** Format: int32 */
            perPage: number | string;
            data: components["schemas"]["SearchIssueDto"][];
            hasNextPage: boolean;
            hasPreviousPage?: boolean;
        };
        SortingDirection: number;
        SpaceDetailsDto: {
            canCreateEpics: boolean;
            canUpdate: boolean;
            canDelete: boolean;
        };
        SpaceListDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: string;
            key: string;
            isDefault: boolean;
        };
        SpaceMember: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            initials: string;
            color: string;
        };
        StatusDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: null | string;
            /** Format: int32 */
            sortOrder: number | string;
        };
        TelegramWidgetAuthRequest: {
            /** Format: int64 */
            id?: number | string;
            first_name?: string;
            last_name?: null | string;
            username?: null | string;
            photo_url?: null | string;
            /** Format: int64 */
            auth_date?: number | string;
            hash?: string;
        };
        UpdateAttributeListValueDto: {
            /** Format: int64 */
            id?: null | number | string;
            name: string;
        };
        UpdateAttributeRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            id?: number | string;
            name: string;
            color: string;
            listValues: null | components["schemas"]["UpdateAttributeListValueDto"][];
        };
        UpdateEpicRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            id?: number | string;
            name: string;
            color: string;
        };
        UpdateSpaceRequest: {
            authData?: components["schemas"]["OrganizationAuthData"];
            /** Format: int64 */
            id?: number | string;
            name: string;
            color: string;
            key: string;
        };
        UserDto: {
            /** Format: int64 */
            telegramId?: number | string;
            username?: null | string;
            firstName?: null | string;
            lastName?: null | string;
            languageCode: string;
            color: string;
            initials?: null | string;
            palette: string[];
            preferences?: components["schemas"]["UserPreferencesResponse"];
        };
        UserOrganizationPreferencesResponse: {
            /** Format: int64 */
            selectedSpaceId?: null | number | string;
        };
        UserPermissions: {
            global?: components["schemas"]["GlobalAccessLevels"];
            direct?: {
                [key: string]: components["schemas"]["DirectSpaceAccessLevel"];
            };
            admin?: components["schemas"]["AdminAccessLevel"];
        };
        UserPreferencesResponse: {
            epicSortOrder?: components["schemas"]["EpicSortOrder"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
